import Head from 'next/head'

export default function Home() {
  return (
    <div className='bg-slate-600'>
      <Head>
        <title>Futsal Manager</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>Home</div>
      </main>
    </div>
  )
}
